name: "CI"

on:
  push:
  pull_request:

jobs:
  build:
    name: "🏗️ Build"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [14, 16, 17]
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Node.js"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
      - name: "♻️ Cache dependencies"
        uses: actions/cache@v4.0.1
        with:
          path: |
            node_modules
            build
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - name: "🧰 Install dependencies"
        run: yarn install
      - name: "🏗️ Build package"
        run: yarn build
  deploy:
    name: "📤 Deploy"
    needs:
      - build
    runs-on: ubuntu-20.04
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
      - name: "🧰 Install Node.js"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 17
      - name: "♻️ Cache dependencies"
        uses: actions/cache@v4.0.1
        with:
          path: |
            node_modules
            build
          key: ${{ runner.os }}-node-${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
      - name: "🧰 Install dependencies"
        run: yarn install
      - name: "🏗️ Build package"
        run: yarn build
      - name: "🚀 Deploy to GitHub pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
